#! /usr/bin/env bash

sudo sysctl net.ipv4.ip_forward=1
sudo sysctl net.ipv6.conf.all.disable_ipv6=0
sudo sysctl net.ipv6.conf.all.forwarding=1
case $(hostname) in
    DBR1)
        addr_octet=1
        first_int=1122
        lo_addrs=("2001:db8:1111:1::1/64" "2001:db8:1111:2::1/64" "2001:db8:1111:3::1/64" "2001:db8:1111:4::1/64")
        ;;
    DBR2)
        addr_octet=2
        first_int=1122
        second_int=2233
        third_int=2244
        ;;
    DBR3)
        addr_octet=3
        first_int=2233
        lo_addrs=("2001:db8:3333:1::3/64" "2001:db8:3333:2::3/64")
        ;;
    DBR4)
        addr_octet=4
        first_int=2244
        lo_addrs=("2001:db8:4444:1::4/64" "2001:db8:4444:2::4/64")
        ;;
    *)
        echo "unknown hostname"
        ;;
esac
sudo ip addr add 172.20.$addr_octet.$addr_octet/32 dev lo
sudo ip addr add 2001:db8:eeee:$addr_octet::$addr_octet/64 dev lo
sudo ip addr add 2001:db8:$first_int::$addr_octet/64 dev eth1
if [[ $(hostname) = DBR2 ]]; then
    sudo ip addr add 2001:db8:$second_int::$addr_octet/64 dev eth2
    sudo ip addr add 2001:db8:$third_int::$addr_octet/64 dev eth3
else
    sudo ip link add name dummy0 type dummy
    sudo ip link set dummy0 up
    for addr in "${lo_addrs[@]}"; do
        sudo ip addr add "$addr" dev dummy0
    done
fi
sudo apt -y install vim libreadline-dev
wget ftp://bird.network.cz/pub/bird/bird-2.0.2.tar.gz
tar xf bird-2.0.2.tar.gz
cd bird-2.0.2/
./configure --sbindir=/usr/local/bin --sysconfdir=/etc/bird
make
sudo make install
cd
wget http://ftp.us.debian.org/debian/pool/main/b/bird/bird_1.6.3-2_amd64.deb
ar vx bird_1.6.3-2_amd64.deb
unxz data.tar.xz
tar xf data.tar
sudo bash -c "sed 's/usr\/sbin/usr\/local\/bin/' lib/systemd/system/bird.service > /etc/systemd/system/bird.service"
sudo cp etc/bird/envvars /etc/bird/
sudo cp -r usr/lib/bird /usr/lib/
sudo useradd -s /bin/none -U bird
sudo systemctl start bird.service
