Vagrant.configure("2") do |config|
  config.vm.define "r1" do |r1|
      r1.vm.box = "generic/debian9"
      r1.vm.hostname = "DBR1"
      r1.vm.network "private_network", ip: "192.168.12.1", virtualbox_intnet: "nix12"
      r1.vm.provision "shell", path: "deb_bird_prov"
  end

  config.vm.define "r2" do |r2|
      r2.vm.box = "generic/debian9"
      r2.vm.hostname = "DBR2"
      r2.vm.network "private_network", ip: "192.168.12.2", virtualbox_intnet: "nix12"
      r2.vm.network "private_network", ip: "10.1.23.2", virtualbox_intnet: "nix23"
      r2.vm.network "private_network", ip: "10.1.24.2", virtualbox_intnet: "nix24"
      r2.vm.provision "shell", path: "deb_bird_prov"
  end

  config.vm.define "r3" do |r3|
      r3.vm.box = "generic/debian9"
      r3.vm.hostname = "DBR3"
      r3.vm.network "private_network", ip: "10.1.23.3", virtualbox_intnet: "nix23"
      r3.vm.provision "shell", path: "deb_bird_prov"
  end

  config.vm.define "r4" do |r4|
      r4.vm.box = "generic/debian9"
      r4.vm.hostname = "DBR4"
      r4.vm.network "private_network", ip: "10.1.24.4", virtualbox_intnet: "nix24"
      r4.vm.provision "shell", path: "deb_bird_prov"
  end
end
